package com.esgi.nova.application.uses_cases.users.exceptions

class UserNotFoundByIdException : Throwable() {

}
